### ISSUE TITLE
Dataset not found

### ISSUE THREAD

**Issue by DeepLearner7** [Aniruddha-Tapas/Speech-Recognition-of-Digits-using-Tensorflow#3]
I am not able to download dataset from  http://pannous.net/files/spoken_numbers_pcm.tar
Please help.

**Comment by Aniruddha-Tapas** [comment]
Hi, the original project migrated to https://github.com/pannous/tensorflow-speech-recognition. So you can now download the tar file from [here](https://github.com/pannous/tensorflow-speech-recognition/blob/master/spoken_numbers_pcm.tar).
